"use client";

import { motion } from "framer-motion";
import { PageWrapper } from "@/components/layout/PageWrapper";
import { usePageMeta } from "@/lib/seo";

export default function TermsPage() {
  usePageMeta(
    "Terms & Conditions | Travio GPS Tracking",
    "Read Travio's terms and conditions for GPS tracking products and services. Understand your rights and obligations.",
  );

  return (
    <PageWrapper>
      {/* Hero Section */}
      <section className="pt-32 pb-12 lg:pt-40 lg:pb-16 bg-card">
        <div className="container-premium">
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="max-w-3xl"
          >
            <p className="text-sm uppercase tracking-[0.3em] text-accent mb-4">Legal</p>
            <h1 className="font-serif text-display-3 md:text-display-2 text-foreground mb-6">
              Terms & <span className="italic-accent">Conditions</span>
            </h1>
            <p className="text-muted-foreground">
              Last updated: {new Date().toLocaleDateString('en-GB', { month: 'long', year: 'numeric' })}
            </p>
          </motion.div>
        </div>
      </section>

      {/* Content */}
      <section className="section-padding bg-background">
        <div className="container-premium">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="max-w-3xl prose prose-invert prose-headings:font-serif prose-headings:text-foreground prose-p:text-muted-foreground prose-a:text-accent prose-strong:text-foreground"
          >
            <h2>1. Introduction</h2>
            <p>
              These Terms and Conditions govern your use of the Travio GPS Tracking website 
              and the tracking services we provide. By accessing our platform or using our devices, 
              you agree to be bound by these terms.
            </p>

            <h2>2. About Us</h2>
            <p>
              Travio GPS Tracking is a trading name of Travio Technology Limited, 
              a company registered in England and Wales. We provide professional-grade 
              GPS tracking software and hardware for personal and commercial use.
            </p>

            <h2>3. Services & Subscriptions</h2>
            <p>We provide the following GPS tracking services:</p>
            <ul>
              <li>Real-time vehicle and asset tracking</li>
              <li>Fleet management software (GPSLive)</li>
              <li>Subscription-based data plans</li>
              <li>Installation services for insurance-approved trackers</li>
            </ul>
            <p>
              Subscription services are billed in advance and are required for the continued 
              operation of most tracking hardware. Failure to maintain an active subscription 
              will result in service suspension.
            </p>

            <h2>4. Hardware & Use</h2>
            <h3>Accuracy & Coverage</h3>
            <p>
              While we use advanced GPS and cellular technology, tracking accuracy and 
              real-time updates may be affected by signal obstructions, atmospheric 
              conditions, or cellular network availability.
            </p>
            <h3>Installation</h3>
            <p>
              Self-install devices (OBD, Battery-connect) must be fitted according to our instructions. 
              Insurance-approved (S5/S7) devices must be installed by an authorized technician 
              to maintain their certification.
            </p>
            <h3>Intellectual Property</h3>
            <p>
              The GPSLive platform, its interface, algorithms, and all content on this website 
              are protected by copyright and intellectual property laws. You may not reverse-engineer 
              our hardware or software.
            </p>

            <h2>5. Service Limitations</h2>
            <p>
              We aim for 99.9% platform uptime but do not guarantee uninterrupted service. 
              Maintenance windows and external network outages may occasionally affect access.
            </p>

            <h2>6. Data Ownership</h2>
            <p>
              You own the location data generated by your devices. We act as a data processor 
              to store and present this data to you. We will not sell your specific location 
              history to third parties.
            </p>

            <h2>7. Prohibited Use</h2>
            <p>You agree not to use Travio tracking services for:</p>
            <ul>
              <li>Unlawful tracking of individuals without their consent</li>
              <li>Harassment or stalking</li>
              <li>Illegal activities or monitoring law enforcement</li>
            </ul>

            <h2>8. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Travio shall not be 
              liable for any indirect, incidental, or consequential damages arising from 
              device failure, battery depletion, or signal loss, particularly in the 
              event of vehicle theft.
            </p>

            <h2>9. Termination</h2>
            <p>
              You may cancel your subscription at any time via your account dashboard. 
              Refunds for unused portions of pre-paid subscriptions are subject to our 
              return policy.
            </p>

            <h2>10. Governing Law</h2>
            <p>
              These Terms and Conditions are governed by English law. Any disputes shall be 
              subject to the exclusive jurisdiction of the courts of England and Wales.
            </p>

            <h2>11. Contact</h2>
            <p>
              For questions about these Terms and Conditions, please contact us at:
            </p>
            <p>
              <strong>Travio GPS Tracking</strong><br />
              123 Tech Plaza<br />
              London, EC1A 1BB<br />
              Email: legal@traviogps.com<br />
              Phone: 01246 567 540
            </p>
          </motion.div>
        </div>
      </section>
    </PageWrapper>
  );
}
